// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Cuv_ranksum_nulldist
NumericVector Cuv_ranksum_nulldist(NumericVector x, int nsim, int Ei);
RcppExport SEXP _treestructure_Cuv_ranksum_nulldist(SEXP xSEXP, SEXP nsimSEXP, SEXP EiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    Rcpp::traits::input_parameter< int >::type Ei(EiSEXP);
    rcpp_result_gen = Rcpp::wrap(Cuv_ranksum_nulldist(x, nsim, Ei));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treestructure_Cuv_ranksum_nulldist", (DL_FUNC) &_treestructure_Cuv_ranksum_nulldist, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_treestructure(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
