# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export 
Cuv_ranksum_nulldist <- function(x, nsim, monomono) {
    .Call(`_treestructure_Cuv_ranksum_nulldist`, x, nsim, monomono)
}

